name: CI

on:
  pull_request:
    branches: [master]
    paths-ignore: [website/**]
  push:
    branches: [master]
    paths-ignore: [website/**]

jobs:
  test:
    name: Node ${{matrix.node_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{matrix.node_version}}

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Integrity check
        run: yarn bob check

  lint:
    name: Lint
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@main
    with:
      script: yarn ci:lint
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    name: Lint source files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 16

      - name: Lint Prettier
        run: yarn prettier:check
