name: Canary Release

on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@main
    with:
      preCommit: 'pnpm run prettier'
      installDependencies: true
      packageManager: 'pnpm'
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}

  canary:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
      packageManager: 'pnpm'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}

  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-integrity.yml@main
    with:
      domain: https://www.the-guild.dev/graphql/config/
      source: 'Config'
      setupEnvWorkingDirectory: './website'
      packageManager: 'pnpm'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
